- name: creating filter
  hosts: all
  vars:
    URL: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.30.1-01-unix.tar.gz
    tag_data:
      env: dev
      app: nexus
  tasks:
    - name: print url
      debug:
        msg: "{{URL | urlsplit}}"

    - name: print url
      debug:
        msg: "{{URL.split('/')}}"  

    - name: print url
      debug:
        msg: "{{URL.split('|')}}"

   # - name: print url
     #  debug:
      #  msg: "{{URL.split('\')}}" 

    - name: print url
      debug:
        msg: "{{URL.split('*')}}"   

    - name: print tag data
      debug:
        msg: "{{tag_data | dict2items}}"   


    - name: create servers
      debug:
        msg: "{{item.name}}"
      loop:
        - name: server1
          disks: 1gb
          ram: 5gb
          network: 
              nicol: 8gb
              nicol: 3gb
        - name: second server
          disks: 5gb
          ram: 8gb   
           network: 
              nicol: 8gb
              nicol: 3gb          