- name: setup todo 
  hosts: all
  become: yes
  tasks:
    - name: install NGINX
      apt:
        name: nginx
        update_cache: yes
        state: present
      become: yes  

    - name: install npm
      apt:
        name: npm
        update_cache: yes
        state: present
      become: yes 

    - name: Download frontend from Nexus
      get_url:
         url:  http://172.31.15.207:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
         dest: /tmp/frontend.zip
         username: admin
         password: zelar123

    #- name: change the working directory to  /var/www/html 
     # command:  cd /var/www/html
    - name: change the working directory to  /var/www/html
      shell:  /var/www/html
        register: /var/www/html
      become: yes
      debug:
        msg: "{{ /var/www/html }}"     



    #- name: Start Nginx
     # systemd:
      #  state: started
       # name: nginx
        #enable: yes  
