- name: setup todo 
  hosts: all
  become: yes
  tasks:
    - name: install NGINX
      apt:
        name: nginx
        update_cache: yes
        state: present
      become: yes  

    - name: install npm
      apt:
        name: npm
        update_cache: yes
        state: present
      become: yes  

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enable: yes  
