---
- hosts: all
  tasks:
    - name: ensure nginx 
      ansible.builtin.apt: 
      name: nginx 
      state: present
    - name: start nginx
      service:
          name: nginx
          state: started