- hosts: all
  #vars:
   # URL: play.example.com
   # HEello: welcome
  #vars_files:
   # - hello-var.yml  
  #vars_prompt:
   # - name: URL
     # prompt: Enter URL 
     # private: no
  tasks:
    - name: play.example.com
      debug:
        msg: URL = {{ URL }}
    - name: print localtask
      debug:
        msg: URL ={{ URL}}
      vars:
        URL: tasklocal.example.com

- name: demo on dynamical
  hosts: all
  tasks:
    - name: gather date
      shell: date +%F
      register: out
    - name: print date
      debug:
       msg: "Date={{out.stdout}} " 
       
    - name: seting facts
      set_fact:
        Date: "{{out.stdout}}"
    - name: print
      debug:
        msg: "Date={{out.stdout}}"    

- name: print facts
  hosts: all
  tasks:
    - name: ptint facts
      debug:
        msg : hostname = {{ansible-hostname}}          