- hosts: all
  vars:
    URL: play.example.com
    HEello: welcome
  vars_files:
    - hello-var.yml  
  vars_prompt:
    - name: URL
      prompt: Enter URL 
      private: no
  tasks:
    - name: play.example.com
      debug:
        msg: URL = {{ URL }}
    - name: print localtask
      debug:
        msg: URL ={{ URL}}
      vars:
        URL: tasklocal.example.com