- hosts: all
  vars:
    URL: play.example.com
    HEello: welcome
  vars_files:
    - todo.yml  
  tasks:
    - name: play.example.com
      debug:
        msg: URL = {{ URL }}
    - name: print localtask
      debug:
        msg: URL ={{ URL}}
      vars:
        URL: tasklocal.example.com