- hosts: all
  vars:
    URL: play.example.com
    HEello: welcome
  tasks:
    - name: play.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}
    - name: print localtask
        debug:
        msg: URL ={{ URL}}
    vars:
      URL: tasklocal.example.com