---
- name: printing var
  hosts: all
  var:
    URL: play.example.com
    project: example
  tasks:
    - name: play.example.com
      ansible.builtin.debug:
        msg: URL = {{ ping google.com }}
