- name: Install npm
  apt:
    name: npm
    state: present
    update_cache: yes

- name: add todo user
  user:
    name: todoapp
    shell: /bin/bash    

- name: Download todo from Nexus
  get_url:
    url: http://172.31.15.207:8081/repository/todo/todo-{{APP_VERSION}}.zip
    dest: /tmp/todo-main.zip
    username: admin
    password: zelar123

- name: remove the old artifacts
  file:
    path: /home/ubuntu/todo
    state: absent

- name: Create the artifact path
  file:
    path: /home/ubuntu/todo
    state: directory
    owner: ubuntu
    group: ubuntu
  
- name: Extract the todo Content
  unarchive:
    src: /tmp/todo-main.zip
    dest: /home/ubuntu/todo
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy todo Service file
  copy:
    src: Todo.service
    dest: /etc/systemd/system/todo.service

- name: Start todo Service
  systemd:
    name: "todo"
    daemon_reload: yes
    state: started
    enabled: yes