- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Download {{COMPONENT}} from Nexus
  get_url:
    url: http://172.31.15.207:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    username: admin
    password: zelar123

- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    

- name: Create HtDocs Directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Unzip the Downloaded Content
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /var/www/html/frontend
    remote_src: yes

- name: Update Todo Config file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf

- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes