 - name: install NGINX
   apt:
        name: nginx
        update_cache: yes
        state: present
   become: yes  

 - name: install npm
   apt:
        name: npm
        update_cache: yes
        state: present
   become: yes 

 - name: Download frontend from Nexus
   get_url:
         url:  http://172.31.15.207:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
         dest: /tmp/frontend.zip
         username: admin
         password: zelar123

 - name: create the HtDocs directory
   file:
        path: /var/www/html/
        state: directory

 - name: changing location
   command: chdir=/var/www/html/ ls

 - name:  create directory 
   file:
        path: todo
        state: directory

 - name: create directory
   file:
          path: todo/frontend
          state: directory

 - name: changing directory
   command: chdir=todo ls 

 - name: unzip the Downloand content
   unarchive:
        src: /tmp/frontend.zip
        dest: /var/www/html
        remote_src: yes

 - name: npm install and clean
   command: npm run build chdir=/var/www/html/todo/frontend
    #with_items:
     # - npm run build


 - name: install nodejs
   apt:
        name: nodejs
        update_cache: yes

 - name: replace the file
   replace:
        path: /etc/nginx/sites-available/default
        after: /var/www/html
        regexp: '^(.+)$'
        replace: todo/frontend/dist;

 - name: From index.js file
   file:
     src: index.js
     dest: /var/www/html/todo/frontend/todo.cfg       

 #- name: Move Default to other dir
  # command: mv default /etc/nginx/sites-available/default    

# - name: restart nginx
 #  systemd:
  #  name: nginx
   # state: restarted
    #daemon_reload: yes

 #- name: enable nginx
  # systemd:
   # name: nginx
    #state: enable
    #daemon_reload: yes   

 

          