- name: Install GOLANG
  apt:
    name: golang
    state: present
    update_cache: yes

- name: Download login from Nexus
  get_url:
    url: http://3.237.201.182:8081/repository/login/login-{{APP_VERSION}}.zip
    dest: /tmp/login-main.zip
    username: admin
    password: zelar123

- name: Clean the old artifacts
  file:
    path: /home/ubuntu/login
    state: absent

- name: Create the artifact path
  file:
    path: /home/ubuntu/login
    state: directory
    owner: ubuntu
    group: ubuntu
  
- name: Extract the login Content
  unarchive:
    src: /tmp/login.zip
    dest: /home/ubuntu/login
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy login Service file
  copy:
    src: login.service
    dest: /etc/systemd/system/login.service

- name: Start login Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes